import SideBar from './components/SideBar'
import './globals.css'
import { Baloo_Bhai_2 } from 'next/font/google'
import { Providers } from './provider'
import { GlobalProvider } from '@/context/Context'

const inter = Baloo_Bhai_2({ subsets: ['gujarati'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalProvider>
          <Providers>
            <div className={`flex  justify-start gap-8 p-7 min-h-screen w-full bg-[#F1F0E8]`}>
              <SideBar />
              {children}
            </div>
          </Providers>
        </GlobalProvider>
      </body>
    </html>
  )
}
